language: android
sudo: true
git:
  depth: 3
android:
  components:
    # The SDK version used to compile your project
    - android-28

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28
install:
  - echo y | sdkmanager "ndk-bundle"
before_script:
  - wget https://s3.amazonaws.com/download.onnx/models/opset_9/squeezenet.tar.gz && tar xf squeezenet.tar.gz
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
  - echo no | android create avd --force -n test -t android-28 --abi x86
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
  - mkdir build_android && cd build_android
  - cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang -DCMAKE_ANDROID_STL_TYPE=c++_static -DCMAKE_SYSTEM_VERSION=28 ..
  - cmake --build . -- "-j$(nproc)"
  - cd ..
  - mkdir build_onnx2daq && cd build_onnx2daq
  - cmake ..
  - cmake --build . -- "-j$(nproc)"
  - cd ..
  - python3 validate_onnx.py squeezenet/model.onnx build_onnx2daq/tools/onnx2daq/onnx2daq build_android/binaries/dnn_infer softmaxout_1 squeezenet/test_data_set_0/
